### PR TITLE
upgrade: bytes 1.0, tokio 1.0

### PR DESCRIPTION
**Pull request by bartlomieju**

### CODE REVIEW

**Comment by darinmorrison** [comment]
There's actually a `tokio-1.0` branch that has a few more changes which fix some of the failing tests here so I'll just merge that one and make a new release. But thanks for the PR!

**Comment by bartlomieju** [comment]
@darinmorrison thanks, any chance for a release tonight?

**Comment by darinmorrison** [comment]
@bartlomieju sure. I just published a new version.

**Comment by bartlomieju** [comment]
Thanks!

**Pull request closed without merging**
